services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ega-mba-landing:latest
    container_name: ega-mba-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
